services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    # No public ports exposed for the server, it will be accessed via Next.js rewrites on the internal network
    env_file:
      - ./apps/server/.env
    environment:
      - DATABASE_URL=mysql://root:rishabh11@host.docker.internal:3306/otbl
      - NODE_ENV=production
    networks:
      - otbl-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    networks:
      - otbl-network

networks:
  otbl-network:
    driver: bridge
